image: docker:20.10.2
services:
  - docker:20.10.2-dind

stages:
  - build-version
  - build
  - test
  - release

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  CONTAINER_TEST_IMAGE: $CONTAINER_RELEASE_IMAGE-1.$CI_PIPELINE_IID
  BASE_IMAGE: "debian:bullseye-slim"

build-version:
  stage: build-version
  image: $BASE_IMAGE  
  only: 
    - tags
  script:
    - ./build.sh $CI_COMMIT_TAG
  artifacts:
    paths:
      - versions/

build:
  stage: build
  only: 
    - tags
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd versions/$CI_COMMIT_TAG/alpine/apache/php73/
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE    

release-image:
  stage: release
  only: 
    - tags
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # tag the test image for release and push
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE


