# File: docker-compose.yml
# Access via "http://localhost:8081"
#
# Call example:
# $ docker-compose up

version: "3.6"

networks:
  inside:
    external: false

services:
  db:
    image: mariadb:10.2
    env_file:
      - .env
    container_name: "ojs_db_${COMPOSE_PROJECT_NAME:-demo}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-ojs}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-ojs2}"
      MYSQL_USER: "${MYSQL_USER:-ojs}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-ojs}"
    networks:
      - inside
    restart: always

  ojs:
    image: local/ojs:3_0b1
    env_file:
      - .env
    container_name: "ojs_app_${COMPOSE_PROJECT_NAME:-demo}"
    hostname: "${COMPOSE_PROJECT_NAME:-demo}"
    restart: always
    ports:
      - "${HTTP_PORT:-8080}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - /etc/localtime:/etc/localtime
       # Create files or folders first and check permisions, to avoid errors:
#      - ./volumes/private:/var/www/files
#      - ./volumes/public:/var/www/html/public
#      - ./volumes/db:/var/lib/mysql
#      - ./volumes/logs:/var/log/apache2
#      - ./config/ojs.config.inc.php:/var/www/html/config.inc.php
#      - ./config/apache.htaccess:/var/www/html/.htaccess
#      - ./config/php.custom.ini:/usr/local/etc/php/conf.d/custom.ini

    networks:
      - inside
    depends_on:
      - db
    restart: always
